language: android
sudo: required
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

before_script:
  - chmod +x ./gradlew
  - echo yes | sdkmanager "build-tools;29.0.3"
  - echo no | android create avd --force -n test -k "system-images;android-R;google_apis_playstore;x86"
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
    ./gradlew check build test connectedAndroidTest && ./gradlew assembleRelease
